### ISSUE TITLE
mvnrepository version still 2.3.2 

### ISSUE THREAD

**Issue by acshmily** [penggle/kaptcha#5]
kaptcha version 2.3.2 have some security problem
plz update mvnrepository version
thx

**Comment by ellenbboe** [comment]
![image](https://user-images.githubusercontent.com/24969128/72681721-4b25dc80-3b01-11ea-8f52-5b677ab3c5f0.png)

**Comment by zhanglei-tech** [comment]
源码已经修复了，能不能麻烦把maven仓库升级一下版本呢

**Comment by 721806280** [comment]
源码已经修复了，能不能麻烦把maven仓库升级一下版本呢

**Comment by acshmily** [comment]
自己实现吧，可以不依赖这个
